### ISSUE TITLE
Not working with operator mono italic font any longer

### ISSUE THREAD

**Issue by mtin79** [kcmr/electron-theme-vscode#1]
hi there,
is is my favourite theme.
unfortunately it doesn't seem to support the italic operator font for ligatures any longer.
any fixes or settings I need to consider?

thanks for help!

**Comment by kcmr** [comment]
I've removed the italics because it's more readable for me. I don't use Operator Mono anymore.
You can restore that settings by adding the following to your preferences file inside `"editor.tokenColorCustomizations"`:

```json
"[Electron]": {
    "textMateRules": [
        {
            "scope": "entity.other.attribute-name",
            "settings": {
                "fontStyle": "italic"
            }
        },
        {
            "scope": "support.type, support.class",
            "settings": {
                "fontStyle": "italic"
            }
        }
    ]
}
```

Hope it helps you.

**Comment by mtin79** [comment]
Amazing, thank you very much!
This is the best theme ever :-)

For others and future lookups, this is what I added to my Settings to make it work with Operator Mono Italic Fonts:

```
  "workbench.colorTheme": "Electron",
  "editor.fontFamily": "Operator Mono",
  "editor.fontWeight": "200",
  "editor.fontSize": 12,
  "editor.tabSize": 2,
  "editor.tokenColorCustomizations": {
    "[Electron]": {
      "textMateRules": [
        {
          "scope": "entity.other.attribute-name",
          "settings": {
            "fontStyle": "italic"
          }
        },
        {
          "scope": "support.type, support.class",
          "settings": {
            "fontStyle": "italic"
          }
        }
      ]
    }
  }
```

**Comment by kcmr** [comment]
Perfect! Closing the issue.

**Comment by alestry-perez** [comment]
> I've removed the italics because it's more readable for me. I don't use Operator Mono anymore. You can restore that settings by adding the following to your preferences file inside `"editor.tokenColorCustomizations"`:
> 
> ```json
> "[Electron]": {
>     "textMateRules": [
>         {
>             "scope": "entity.other.attribute-name",
>             "settings": {
>                 "fontStyle": "italic"
>             }
>         },
>         {
>             "scope": "support.type, support.class",
>             "settings": {
>                 "fontStyle": "italic"
>             }
>         }
>     ]
> }
> ```
> 
> Hope it helps you.

This is what I've been looking for to customize some other theme for my workspace thank you! I didn't know I could do this.
