### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by mikemcbride** [kcmr/electron-theme-vscode#2]
Would appreciate if you gave me some acknowledgement since I wrote this theme for Atom. Maybe a link or something to the repo. Thanks.

**Comment by kcmr** [comment]
Of course! Your theme is already mentioned in the description but I'll add a link to your repo.

**Comment by kcmr** [comment]
I've added a link to your repo so I'm closing the issue. I should did that since the beginning, as I did for the [Sublime Text version](https://github.com/kcmr/electron-theme). Sorry about that.

**Comment by mikemcbride** [comment]
Thanks! No worries, appreciate you doing that 😊
