### ISSUE TITLE
support for markdown syntax

### ISSUE THREAD

**Issue by FilipeBento** [kcmr/electron-theme-vscode#5]
Hello, this is my first issue on Github. I find the theme absolutely fantastic. Unfortunately it doesn't provide support for markdown syntax out of the box. Here's what it looks like ( vs Dracula Theme):

![image](https://user-images.githubusercontent.com/2933045/139770166-f9339e91-2cdf-4a22-9a79-2bec89da082d.png)
![image](https://user-images.githubusercontent.com/2933045/139770197-b10325be-1009-4488-b769-d5f14fadbe75.png)

Can you guide me on the best way of adding it? :)

Thank you for your work on the theme.

**Comment by kcmr** [comment]
Hi @FilipeBento 

Thank you for offering your contribution to the theme.

What I usually do is picking a theme that I like and want to use as a reference and, with the theme in use, I select from the command palette "Developer: Generate Color Theme From Current Settings". This command generates a JSON file with all the colors used by the current theme for the editor and the languages. Language colors (syntaxes for specific languages) are under `tokenColors`. Here you can pick the missing colors for markdown and adjust to your preferences.

Here are two links that can help you with the process of trying the colors in the editor:

- https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme
- https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme

Looking forward to see your contribution :)

**Comment by FilipeBento** [comment]
I am working on this feature when I have the time. I have a small,
unrelated, request. I don't have your email so here it is. Perhaps it's my
monitor that's outdated and has terrible colours, but I am working with
some .gitignored files in a repo and in VSCode the dark grey colour used in
the filename is way too dark. I will post a screenshot in a bit. Is it
possible to modify the colors to still differentiate it while being
readable?

**Comment by kcmr** [comment]
Yes. I personally like the ignored folders and files to be super faded to not distract me, but you can change that colors to your preferences without the need to change the original theme. 

The one that you need to customize is `gitDecoration.ignoredResourceForeground`, so you can add it to your settings file (settings.json) under `workbench.colorCustomizations`. 

For instance:

```json
  "workbench.colorCustomizations": {
    "[Electron]": {
      "gitDecoration.ignoredResourceForeground": "#3d4d67", // -> this is the current color
    }
  },
```

**Comment by kcmr** [comment]
You also can customize other aspects of the editor (not the syntax colors) that you don't like the same way. Some years ago I did a small project for this. It seems that it still works 😅, at least on Chrome. You can give it a try here: https://color-your-code.firebaseapp.com/

**Comment by FilipeBento** [comment]
Perfect, then. I will add it to my settings. It's great that vs code is so well structured. It provides a lot of flexibility with very little effort to customize.

**Comment by FilipeBento** [comment]
![image](https://user-images.githubusercontent.com/2933045/140377995-d280902f-e02a-4db5-876b-14f194f9e1ea.png)

How does this look like to you?

**Comment by kcmr** [comment]
Hi @FilipeBento 
It looks perfect! I'm happy to accept a PR :)

**Comment by FilipeBento** [comment]
By using string.unquoted, I converted the color of the first lines to the color of a comment, but I am **not sure how it will impact other languages**, so I removed it.
I got this (which I believe is better than the usual white):
![image](https://user-images.githubusercontent.com/2933045/140560659-d952a542-2944-4900-96f6-4e3a37b02d9a.png)

Everything else seems to be working fine. I did not test it as an extension; I added the settings to my vscode settings, under tokenColors and everything worked well. I am going to open a pull request :) Feel free to make modifications that you see fit. I am not a designer; I copied colors that you used in other parts of the theme, such as HTML tags, strings and json colors. It produced the colors that you saw above.

Let me know if there is something to correct.

**Comment by kcmr** [comment]
Go ahead! I'll take a look to check everything is working fine.
I use the same process to test color changes… it's faster than trying the extension.

**Comment by kcmr** [comment]
I've taken a look at #6 and everything seems to be working fine. Regarding your comment about `string.unquoted`, is this what you want to achieve? See the screenshot below. I don't think it will impact other languages.

<img width="797" alt="Captura de pantalla 2021-11-05 a las 22 24 06" src="https://user-images.githubusercontent.com/92611/140580329-93b8f279-0565-4683-a1c3-58edd13750da.png">


```json
{
  "scope": [
    "string.unquoted.plain.out.yaml",
    "meta.embedded.block.frontmatter"
  ],
  "settings": {
    "foreground": "#506686"
  }
}
```

**Comment by kcmr** [comment]
I think this looks better. How does it look to you?

<img width="673" alt="Captura de pantalla 2021-11-05 a las 22 32 10" src="https://user-images.githubusercontent.com/92611/140581069-9811587b-6984-49e8-9c27-a7ef3c449b35.png">

**Comment by FilipeBento** [comment]
It looks gorgeous! It's a great idea.

**Comment by kcmr** [comment]
Great! I'll merge your PR and include this changes later for the yml embedded comments.
Thank you very much for your contribution :)
